version: "3"
services:
  web:
    build: .
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    environment:
      - PORT=3000
    working_dir: /usr/src/app
    command: ["./wait_for_it.sh", "postgres:5432", "--", "npm", "run", "debug"]
  postgres:
    image: postgres:10.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=listbuilder
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: